/**
 * Generated by Postman Code
 *
 * Collection: PayPal APIs
 * Collection UID: 19024122-92a85d0e-51e7-47da-9f83-c45dcb1cdf24
 *
 * Request: Invoices > Invoices > Create draft invoice
 * Request UID: 19024122-d2903ebb-f4e3-4db8-bd41-b8f33ccef6f6
 * Request modified at: 2025-04-21T22:59:32.000Z
 */

import crypto from 'node:crypto';

/**
 * @typedef {Object} CreateDraftInvoiceMinimalInput
 * @property {string} invoiceDate ISO date (YYYY-MM-DD)
 * @property {string} currencyCode e.g. "USD"
 */

/**
 * @typedef {Object} PayPalInvoiceLink
 * @property {string} href
 * @property {string} rel
 * @property {string} method
 */

/**
 * @typedef {Object} CreateDraftInvoiceResponse
 * @property {string} id e.g. "INV2-APM2-WC6A-8J5E-BLVW"
 * @property {"DRAFT"|string} status
 * @property {{ currency_code?: string, invoice_date?: string, metadata?: any }} detail
 * @property {{ currency_code?: string, value?: string, breakdown?: any }} amount
 * @property {{ currency_code?: string, value?: string }} due_amount
 * @property {PayPalInvoiceLink[]} links
 */

function assertNonEmpty(value, name) {
  if (!value || typeof value !== 'string' || value.trim() === '') {
    throw new Error(`${name} is required`);
  }
}

/**
 * Creates a PayPal draft invoice (minimal payload).
 *
 * Sandbox endpoint: https://api-m.sandbox.paypal.com/v2/invoicing/invoices
 *
 * @param {Object} params
 * @param {string} params.baseUrl e.g. "https://api-m.sandbox.paypal.com"
 * @param {string} params.accessToken OAuth2 bearer token
 * @param {CreateDraftInvoiceMinimalInput} params.input invoiceDate + currencyCode
 * @param {string} [params.payPalRequestId] Optional idempotency key. Generated if omitted.
 * @param {"return=representation"|"return=minimal"} [params.prefer] Defaults to return=representation
 * @returns {Promise<CreateDraftInvoiceResponse>}
 */
export async function createDraftInvoiceMinimal({
  baseUrl,
  accessToken,
  input,
  payPalRequestId,
  prefer = 'return=representation',
}) {
  assertNonEmpty(baseUrl, 'baseUrl');
  assertNonEmpty(accessToken, 'accessToken');
  if (!input || typeof input !== 'object') throw new Error('input is required');
  assertNonEmpty(input.invoiceDate, 'input.invoiceDate');
  assertNonEmpty(input.currencyCode, 'input.currencyCode');

  const url = new URL('/v2/invoicing/invoices', baseUrl);

  const requestId = payPalRequestId ?? crypto.randomUUID();

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
      Accept: 'application/json',
      'PayPal-Request-Id': requestId,
      Prefer: prefer,
    },
    body: JSON.stringify({
      detail: {
        invoice_date: input.invoiceDate,
        currency_code: input.currencyCode,
      },
    }),
  });

  if (res.status === 201) {
    return await res.json();
  }

  const contentType = res.headers.get('content-type') || '';
  const payload = contentType.includes('application/json') ? await res.json() : await res.text();

  const debugId = res.headers.get('paypal-debug-id');
  const message = `PayPal create draft invoice failed: HTTP ${res.status}${debugId ? ` (PayPal-Debug-Id=${debugId})` : ''}`;

  const err = new Error(message);
  err.cause = payload;
  throw err;
}
