// Generated by Postman Code
// Collection: PayPal APIs
// Collection UID: 19024122-92a85d0e-51e7-47da-9f83-c45dcb1cdf24
//
// NOTE: This mirrors relevant Postman collection variables for PayPal Sandbox.
// Secrets (access tokens, client secrets) must be supplied by the caller.

export const variables = {
  collection: {
    base_url: 'https://api-m.sandbox.paypal.com',
    prefer_representation_detailed: 'return=representation',
    prefer_representation_min: 'return=minimal',
  },
};
